export const languages = [
    {
        code: "uk",
        field: "uk",
        suffix: "uk",
        label: "UA",
        flag: "uk.png",
        primary: true,
    },
    {
        code: "en",
        field: "en",
        suffix: "en",
        label: "EN",
        flag: "en.png",
        primary: false,
    },
    {
        code: "pl",
        field: "pl",
        suffix: "pl",
        label: "PL",
        flag: "pl.png",
        primary: false,
    },
    {
        code: "fr",
        field: "fr",
        suffix: "fr",
        label: "FR",
        flag: "fr.png",
        primary: false,
    },
    {
        code: "de",
        field: "de",
        suffix: "de",
        label: "DE",
        flag: "de.png",
        primary: false,
    },
];